FROM node:20-alpine AS base
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY ./package.json ./
COPY ./pnpm-lock.yaml ./
COPY ./pnpm-workspace.yaml  ./
COPY ./turbo.json ./
COPY ./packages ./packages
COPY ./apps/http-backend ./apps/http-backend

RUN pnpm install

RUN npm run generate:db

RUN pnpm turbo build --filter=http-backend...

EXPOSE 3001
CMD [ "npm","run","start:backend"]
