FROM node:20-alpine
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY ./package.json ./
COPY ./pnpm-lock.yaml ./
COPY ./pnpm-workspace.yaml ./
COPY ./turbo.json ./
COPY ./packages ./packages
COPY ./apps/web ./apps/web

RUN pnpm install
RUN npm run generate:db
RUN DB_URL=$DB_URL pnpm turbo build --filter=web...

EXPOSE 3000
CMD ["npm","run","start:ws"]